import type { HardhatPlugin } from "hardhat/types/plugins";
import { task, overrideTask } from "hardhat/config";

import "./type-extensions.js";
import {
  TASK_GAS_REPORTER_MERGE,
  TASK_GAS_REPORTER_MERGE_REPORTS,
  TASK_GAS_REPORTER_START,
  TASK_GAS_REPORTER_STOP,
} from "./task-names.js";

const gasReporterPlugin: HardhatPlugin = {
  id: "hardhat-gas-reporter",
  npmPackage: "hardhat-gas-reporter",
  hookHandlers: {
    config: () => import("./hooks/config.js"),
    hre: () => import("./hooks/hre.js"),
    network: () => import("./hooks/network.js"),
  },
  tasks: [
    overrideTask("test")
      .setAction(() => import("./tasks/test-override.js"))
      .build(),

    task(TASK_GAS_REPORTER_START, "Initialize gas tracking")
      .addFlag({ name: "parallel", description: "Run tests in parallel" })
      .addFlag({ name: "noCompile", description: "Skip compilation" })
      .setAction(() => import("./tasks/start.js"))
      .build(),

    task(TASK_GAS_REPORTER_STOP, "Complete gas reporting")
      .addFlag({ name: "parallel", description: "Run tests in parallel" })
      .setAction(() => import("./tasks/stop.js"))
      .build(),

    task(TASK_GAS_REPORTER_MERGE, "Merge gas reporter output files")
      .addOption({
        name: "output",
        defaultValue: "gasReporterOutput.json",
        description: "Target file to save the merged report",
      })
      .addVariadicArgument({
        name: "input",
        description:
          "A list of JSON data files generated by the gas reporter plugin. " +
          "Files can be defined using glob patterns",
      })
      .setAction(() => import("./tasks/merge-action.js"))
      .build(),

    task(TASK_GAS_REPORTER_MERGE_REPORTS, "Merge reports (internal)")
      .addVariadicArgument({
        name: "inputFiles",
        defaultValue: [],
        description:
          "Path of several gasReporterOutput.json files to merge",
      })
      .setAction(() => import("./tasks/merge-reports-action.js"))
      .build(),
  ],
};

export default gasReporterPlugin;
